/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package domino.vista;

import domino.controlador.ControlDomino;
import domino.events.MovimientoEventHandler;
import domino.modelo.Ficha;
import java.util.ArrayList;
import javax.swing.JButton;
import javax.swing.JFrame;
import javax.swing.JLabel;
import javax.swing.JScrollPane;

/**
 *
 * @author Jesus
 */
public class Domino extends javax.swing.JFrame {

    private MovimientoEventHandler handler;
    //private MovimientoListener listener = new ControlDomino(this);
    private ControlDomino control;
    private Posicion p;

    /**
     * Creates new form Domino
     */
    public Domino() {
        initComponents();
        this.setExtendedState(JFrame.MAXIMIZED_BOTH);
        handler = new MovimientoEventHandler();
        control = new ControlDomino(this);
        handler.addMovimientoListener(control);
        p = new Posicion(this, true);
    }

    public JScrollPane getPanel() {
        return panel;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel3 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        score = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        ficha1 = new javax.swing.JButton();
        ficha2 = new javax.swing.JButton();
        ficha3 = new javax.swing.JButton();
        ficha4 = new javax.swing.JButton();
        ficha5 = new javax.swing.JButton();
        ficha6 = new javax.swing.JButton();
        ficha7 = new javax.swing.JButton();
        ficha8 = new javax.swing.JButton();
        ficha9 = new javax.swing.JButton();
        ficha10 = new javax.swing.JButton();
        ficha11 = new javax.swing.JButton();
        ficha12 = new javax.swing.JButton();
        ficha13 = new javax.swing.JButton();
        ficha14 = new javax.swing.JButton();
        panel = new javax.swing.JScrollPane();

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/usr_vieja1.png"))); // NOI18N

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(153, 153, 153));

        jLabel1.setText("Jugador 1");

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/usr_vieja1.png"))); // NOI18N

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/usr_vieja2.png"))); // NOI18N

        jLabel7.setText("Jugador 2");

        jButton1.setText("Listo");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("Pasar Turno");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        score.setText("0");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(41, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton1)
                    .addComponent(jButton2)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(5, 5, 5)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel4)
                            .addComponent(jLabel7)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addGap(10, 10, 10)
                                    .addComponent(score))
                                .addComponent(jLabel1)))))
                .addGap(28, 28, 28))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(jLabel2)
                .addGap(18, 18, 18)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(score)
                .addGap(38, 38, 38)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel7)
                .addGap(115, 115, 115)
                .addComponent(jButton1)
                .addGap(32, 32, 32)
                .addComponent(jButton2)
                .addContainerGap(213, Short.MAX_VALUE))
        );

        jPanel3.setBackground(new java.awt.Color(204, 204, 204));

        ficha1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ficha1ActionPerformed(evt);
            }
        });

        ficha2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ficha2ActionPerformed(evt);
            }
        });

        ficha3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ficha3ActionPerformed(evt);
            }
        });

        ficha4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ficha4ActionPerformed(evt);
            }
        });

        ficha5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ficha5ActionPerformed(evt);
            }
        });

        ficha6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ficha6ActionPerformed(evt);
            }
        });

        ficha7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ficha7ActionPerformed(evt);
            }
        });

        ficha8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ficha8ActionPerformed(evt);
            }
        });

        ficha9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ficha9ActionPerformed(evt);
            }
        });

        ficha10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ficha10ActionPerformed(evt);
            }
        });

        ficha11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ficha11ActionPerformed(evt);
            }
        });

        ficha12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ficha12ActionPerformed(evt);
            }
        });

        ficha13.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ficha13ActionPerformed(evt);
            }
        });

        ficha14.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ficha14ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(48, 48, 48)
                .addComponent(ficha1, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(ficha2, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(ficha3, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(ficha4, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(ficha5, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(ficha6, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(ficha7, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(ficha8, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(ficha9, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(ficha10, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(ficha11, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(ficha12, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(ficha13, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(ficha14, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(32, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(ficha14, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ficha13, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ficha12, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ficha11, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ficha10, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ficha9, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ficha8, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ficha7, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ficha6, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ficha5, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ficha4, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ficha3, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ficha2, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ficha1, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(panel))
                .addGap(7, 7, 7)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(panel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ficha1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ficha1ActionPerformed
        int lado1 = Integer.parseInt(ficha1.getIcon().toString().substring(11, 12));
        int lado2 = Integer.parseInt(ficha1.getIcon().toString().substring(13, 14));
        if (lado1 == 5 && lado2 == 5) {
            handler.realizarMovimiento(new Ficha(lado1, lado2), 0, control.getCon());
            ficha1.setEnabled(false);
        } else {
            p.setVisible(true);
            int opcion = p.getOpcion();
            handler.realizarMovimiento(new Ficha(lado1, lado2), opcion, control.getCon());
                ficha1.setEnabled(false);
        }
    }//GEN-LAST:event_ficha1ActionPerformed

    private void ficha2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ficha2ActionPerformed
        int lado1 = Integer.parseInt(ficha2.getIcon().toString().substring(11, 12));
        int lado2 = Integer.parseInt(ficha2.getIcon().toString().substring(13, 14));
        if (lado1 == 5 && lado2 == 5) {
            handler.realizarMovimiento(new Ficha(lado1, lado2), 0, control.getCon());
            ficha2.setEnabled(false);
        } else {
            p.setVisible(true);
            int opcion = p.getOpcion();
            handler.realizarMovimiento(new Ficha(lado1, lado2), opcion, control.getCon());
            ficha2.setEnabled(false);
        }
    }//GEN-LAST:event_ficha2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        control.jugadorListo();
        this.jButton1.setEnabled(false);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void ficha3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ficha3ActionPerformed
        int lado1 = Integer.parseInt(ficha3.getIcon().toString().substring(11, 12));
        int lado2 = Integer.parseInt(ficha3.getIcon().toString().substring(13, 14));
        if (lado1 == 5 && lado2 == 5) {
            handler.realizarMovimiento(new Ficha(lado1, lado2), 0, control.getCon());
            ficha3.setEnabled(false);
        } else {
            p.setVisible(true);
            int opcion = p.getOpcion();
            handler.realizarMovimiento(new Ficha(lado1, lado2), opcion, control.getCon());
            ficha3.setEnabled(false);
        }
    }//GEN-LAST:event_ficha3ActionPerformed

    private void ficha4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ficha4ActionPerformed
        int lado1 = Integer.parseInt(ficha4.getIcon().toString().substring(11, 12));
        int lado2 = Integer.parseInt(ficha4.getIcon().toString().substring(13, 14));
        if (lado1 == 5 && lado2 == 5) {
            handler.realizarMovimiento(new Ficha(lado1, lado2), 0, control.getCon());
            ficha4.setEnabled(false);
        } else {
            p.setVisible(true);
            int opcion = p.getOpcion();
            handler.realizarMovimiento(new Ficha(lado1, lado2), opcion, control.getCon());
            ficha4.setEnabled(false);
        }
    }//GEN-LAST:event_ficha4ActionPerformed

    private void ficha5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ficha5ActionPerformed
        int lado1 = Integer.parseInt(ficha5.getIcon().toString().substring(11, 12));
        int lado2 = Integer.parseInt(ficha5.getIcon().toString().substring(13, 14));
        if (lado1 == 5 && lado2 == 5) {
            handler.realizarMovimiento(new Ficha(lado1, lado2), 0, control.getCon());
            ficha5.setEnabled(false);
        } else {
            p.setVisible(true);
            int opcion = p.getOpcion();
            handler.realizarMovimiento(new Ficha(lado1, lado2), opcion, control.getCon());
            ficha5.setEnabled(false);
        }
    }//GEN-LAST:event_ficha5ActionPerformed

    private void ficha6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ficha6ActionPerformed
        int lado1 = Integer.parseInt(ficha6.getIcon().toString().substring(11, 12));
        int lado2 = Integer.parseInt(ficha6.getIcon().toString().substring(13, 14));
        if (lado1 == 5 && lado2 == 5) {
            handler.realizarMovimiento(new Ficha(lado1, lado2), 0, control.getCon());
            ficha6.setEnabled(false);
        } else {
            p.setVisible(true);
            int opcion = p.getOpcion();
            handler.realizarMovimiento(new Ficha(lado1, lado2), opcion, control.getCon());
            ficha6.setEnabled(false);
        }
    }//GEN-LAST:event_ficha6ActionPerformed

    private void ficha7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ficha7ActionPerformed
        int lado1 = Integer.parseInt(ficha7.getIcon().toString().substring(11, 12));
        int lado2 = Integer.parseInt(ficha7.getIcon().toString().substring(13, 14));
        if (lado1 == 5 && lado2 == 5) {
            handler.realizarMovimiento(new Ficha(lado1, lado2), 0, control.getCon());
            ficha7.setEnabled(false);
        } else {
            p.setVisible(true);
            int opcion = p.getOpcion();
            handler.realizarMovimiento(new Ficha(lado1, lado2), opcion, control.getCon());
            ficha7.setEnabled(false);
        }
    }//GEN-LAST:event_ficha7ActionPerformed

    private void ficha8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ficha8ActionPerformed
        int lado1 = Integer.parseInt(ficha8.getIcon().toString().substring(11, 12));
        int lado2 = Integer.parseInt(ficha8.getIcon().toString().substring(13, 14));
        if (lado1 == 5 && lado2 == 5) {
            handler.realizarMovimiento(new Ficha(lado1, lado2), 0, control.getCon());
            ficha8.setEnabled(false);
        } else {
            p.setVisible(true);
            int opcion = p.getOpcion();
            handler.realizarMovimiento(new Ficha(lado1, lado2), opcion, control.getCon());
            ficha8.setEnabled(false);
        }
    }//GEN-LAST:event_ficha8ActionPerformed

    private void ficha9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ficha9ActionPerformed
        int lado1 = Integer.parseInt(ficha9.getIcon().toString().substring(11, 12));
        int lado2 = Integer.parseInt(ficha9.getIcon().toString().substring(13, 14));
        if (lado1 == 5 && lado2 == 5) {
            handler.realizarMovimiento(new Ficha(lado1, lado2), 0, control.getCon());
            ficha9.setEnabled(false);
        } else {
            p.setVisible(true);
            int opcion = p.getOpcion();
            handler.realizarMovimiento(new Ficha(lado1, lado2), opcion, control.getCon());
            ficha9.setEnabled(false);
        }
    }//GEN-LAST:event_ficha9ActionPerformed

    private void ficha10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ficha10ActionPerformed
        int lado1 = Integer.parseInt(ficha10.getIcon().toString().substring(11, 12));
        int lado2 = Integer.parseInt(ficha10.getIcon().toString().substring(13, 14));
        if (lado1 == 5 && lado2 == 5) {
            handler.realizarMovimiento(new Ficha(lado1, lado2), 0, control.getCon());
            ficha10.setEnabled(false);
        } else {
            p.setVisible(true);
            int opcion = p.getOpcion();
            handler.realizarMovimiento(new Ficha(lado1, lado2), opcion, control.getCon());
            ficha10.setEnabled(false);
        }
    }//GEN-LAST:event_ficha10ActionPerformed

    private void ficha11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ficha11ActionPerformed
        int lado1 = Integer.parseInt(ficha11.getIcon().toString().substring(11, 12));
        int lado2 = Integer.parseInt(ficha11.getIcon().toString().substring(13, 14));
        if (lado1 == 5 && lado2 == 5) {
            handler.realizarMovimiento(new Ficha(lado1, lado2), 0, control.getCon());
            ficha11.setEnabled(false);
        } else {
            p.setVisible(true);
            int opcion = p.getOpcion();
            handler.realizarMovimiento(new Ficha(lado1, lado2), opcion, control.getCon());
            ficha11.setEnabled(false);
        }
    }//GEN-LAST:event_ficha11ActionPerformed

    private void ficha12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ficha12ActionPerformed
        int lado1 = Integer.parseInt(ficha12.getIcon().toString().substring(11, 12));
        int lado2 = Integer.parseInt(ficha12.getIcon().toString().substring(13, 14));
        if (lado1 == 5 && lado2 == 5) {
            handler.realizarMovimiento(new Ficha(lado1, lado2), 0, control.getCon());
            ficha12.setEnabled(false);
        } else {
            p.setVisible(true);
            int opcion = p.getOpcion();
            handler.realizarMovimiento(new Ficha(lado1, lado2), opcion, control.getCon());
            ficha12.setEnabled(false);
        }
    }//GEN-LAST:event_ficha12ActionPerformed

    private void ficha13ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ficha13ActionPerformed
        int lado1 = Integer.parseInt(ficha13.getIcon().toString().substring(11, 12));
        int lado2 = Integer.parseInt(ficha13.getIcon().toString().substring(13, 14));
        if (lado1 == 5 && lado2 == 5) {
            handler.realizarMovimiento(new Ficha(lado1, lado2), 0, control.getCon());
            ficha13.setEnabled(false);
        } else {
            p.setVisible(true);
            int opcion = p.getOpcion();
            handler.realizarMovimiento(new Ficha(lado1, lado2), opcion, control.getCon());
            ficha13.setEnabled(false);
        }
    }//GEN-LAST:event_ficha13ActionPerformed

    private void ficha14ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ficha14ActionPerformed
        int lado1 = Integer.parseInt(ficha14.getIcon().toString().substring(11, 12));
        int lado2 = Integer.parseInt(ficha14.getIcon().toString().substring(13, 14));
        if (lado1 == 5 && lado2 == 5) {
            handler.realizarMovimiento(new Ficha(lado1, lado2), 0, control.getCon());
            ficha14.setEnabled(false);
        } else {
            p.setVisible(true);
            int opcion = p.getOpcion();
            handler.realizarMovimiento(new Ficha(lado1, lado2), opcion, control.getCon());
            ficha14.setEnabled(false);
        }
    }//GEN-LAST:event_ficha14ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        handler.pasarTurno(control.getCon());
    }//GEN-LAST:event_jButton2ActionPerformed

    public ArrayList getBotones() {
        ArrayList<JButton> botones = new ArrayList();
        botones.add(ficha1);
        botones.add(ficha2);
        botones.add(ficha3);
        botones.add(ficha4);
        botones.add(ficha5);
        botones.add(ficha6);
        botones.add(ficha7);
        botones.add(ficha8);
        botones.add(ficha9);
        botones.add(ficha10);
        botones.add(ficha11);
        botones.add(ficha12);
        botones.add(ficha13);
        botones.add(ficha14);
        return botones;
    }

    public JLabel getScore(){
        return score;
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Domino.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Domino.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Domino.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Domino.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Domino().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ficha1;
    private javax.swing.JButton ficha10;
    private javax.swing.JButton ficha11;
    private javax.swing.JButton ficha12;
    private javax.swing.JButton ficha13;
    private javax.swing.JButton ficha14;
    private javax.swing.JButton ficha2;
    private javax.swing.JButton ficha3;
    private javax.swing.JButton ficha4;
    private javax.swing.JButton ficha5;
    private javax.swing.JButton ficha6;
    private javax.swing.JButton ficha7;
    private javax.swing.JButton ficha8;
    private javax.swing.JButton ficha9;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane panel;
    private javax.swing.JLabel score;
    // End of variables declaration//GEN-END:variables
}
